- .autod.conf.js
- .eslintignore
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- .travis.yml
- README.md
- agent.js
- app.js
- app/extend/context.js
- appveyor.yml
- config/config.default.js
- lib/loader.js
- package.json
- test/fixtures/apps/model-app/app/model/test.js
- test/fixtures/apps/model-app/app/router.js
- test/fixtures/apps/model-app/config/config.js
- test/plugin.test.js
> feat: remove mysql bind

- .gitignore
- README.md
- lib/loader.js
- test/fixtures/apps/model-app/app/model/user.js
- test/plugin.test.js
> chore: complete unittest

- README.md
> docs: add info about how to enable sequelize plugin

- README.md
- lib/loader.js
> feat: use underscore style column name as default

- README.md
> docs: add Suggestions and License

- .sequelizerc
- README.md
- bin/egg-sequelize
- database.js
- package.json
with: eggjs/egg#656
详见 README 新增的内容
> Add `egg-sequelize` bin for Sequelize migrations support.

- README.md
Sequelize Instance use internal `dataValues` for JSON serialization.
Directly assigned attributes will not be included in JSON string.
> docs(readme): fix the full example with association

- README.md
> docs: add sync docs

- lib/loader.js
- test/fixtures/apps/model-app/app/model/post.js
- test/fixtures/apps/model-app/app/model/user.js
- test/plugin.test.js
> fix: init associate should after load of models

- History.md
> docs: update history

- README.md
> docs: fix migration url

- README.md
> Add a migration example for show up use `co.wrap`.

- package.json
> deps: update dependencies

- README.md
> docs(README): fix a typo

- README.md
close [#1565](https://github.com/eggjs/egg/issues/1565)
> docs: fix db sync doc

- README.md
- lib/database.js
https://github.com/eggjs/egg/issues/2060
> fix: EGG_SERVER_ENV support for seuqlieze cli

- README.md
> docs: fix demo code

- lib/sequelizerc.js
when run `egg-sequelize` , will auto create folder `migrations` and `app/model`
close https://github.com/eggjs/egg/issues/2090
> fix: auto create cli folder

- index.d.ts
- package.json
> chore:TypeScript support.

- index.d.ts
extending config options of sequelize plugin.
> fix: using `sequelize.Options` for  sequelize config.

- package.json
> fix: add index.d.ts to pkg.files

- bin/egg-sequelize.js
- package.json
> feat(sequelize-cli): upgrade to 4.0.0

- lib/loader.js
- package.json
> Retry 3 times on startup when database connect fail in temporary, to avoid Egg start failed.

- index.d.ts
> deps: Update index.d.ts

- lib/loader.js
> chore: logger typo

- README.md
- lib/loader.js
- test/datasources_same_dir.test.js
- test/fixtures/apps/datasources-same-dir/app/model/Person.js
- test/fixtures/apps/datasources-same-dir/app/model/monkey.js
- test/fixtures/apps/datasources-same-dir/app/model/other.js
- test/fixtures/apps/datasources-same-dir/app/model/post.js
- test/fixtures/apps/datasources-same-dir/app/model/user.js
- test/fixtures/apps/datasources-same-dir/config/config.js
- test/fixtures/apps/datasources-same-dir/package.json
> feat: multi datasource support load same models

- README.md
Closes https://github.com/eggjs/egg/issues/3282
> docs: port should be number

- index.d.ts
> feat: support multiple data sources config

- README.md
- package.json
- test/fixtures/apps/model-app/app/controller/users.js
- **egg-sequelize**: `sequelize` dependency upgraded to version `5.0.0`
Upgrade `sequelize` dependency for `egg-sequelize` pluggin to version 5.0.0.
> Sequelize upgrade to v5.0.0

- README.md
> docs: default sequelize upgrade to v5

- .gitignore
- index.d.ts
- test/fixtures/apps/ts/app/controller/home.ts
- test/fixtures/apps/ts/app/model/monkey.ts
- test/fixtures/apps/ts/app/model/user.ts
- test/fixtures/apps/ts/app/router.ts
- test/fixtures/apps/ts/config/config.default.ts
- test/fixtures/apps/ts/config/config.local.ts
- test/fixtures/apps/ts/tsconfig.json
- test/fixtures/apps/ts/typings/index.d.ts
- test/ts.test.js
fix:
https://github.com/eggjs/egg/issues/3659
https://github.com/eggjs/egg/issues/3741
https://github.com/eggjs/egg/issues/3742
> fix: fix declaration error

- index.d.ts
- lib/loader.js
> docs: add comment in index.d.ts

- lib/loader.js
> change: retry when db is busy.

- package.json
> feat: update sequelize to version 6
